changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes - Needs Immediate Attention
      labels:
        - breaking-changes
    - title: New Features - Recently Added
      labels:
        - new-features
    - title: Additional Changes - Update At Earliest Convenience
      labels:
        - additional-changes
    - title: Bugs Report - Updated List
      labels:
        - bugs-report
