export const iconInfo = [
  [
    'outlinecommunicationdirectmessage',
    'direct-message',
    'communication',
    'outline',
  ],
  ['outlinecommunicationchat', 'chat', 'communication', 'outline'],
  ['fillcommunicationchat', 'chat', 'communication', 'fill'],
  ['fillcommunicationspaces', 'spaces', 'communication', 'fill'],
  ['outlinecommunicationspaces', 'spaces', 'communication', 'outline'],
  ['outlinefileattachment', 'attachment', 'file', 'outline'],
  ['outlinecontentposts', 'posts', 'content', 'outline'],
  ['outlinecontentedit', 'edit', 'content', 'outline'],
  ['outlinefilearchive', 'archive', 'file', 'outline'],
  ['outlinecontentcomplete', 'complete', 'content', 'outline'],
  ['outlinecontentstarunfilled', 'star-unfilled', 'content', 'outline'],
  ['outlinecontentclose', 'close', 'content', 'outline'],
  ['outlinecommunicationphone', 'phone', 'communication', 'outline'],
  ['outlinecontentqrcode', 'qr-code', 'content', 'outline'],
  ['outlinealertbelloff', 'bell-off', 'alert', 'outline'],
  ['outlinealertbellon', 'bell-on', 'alert', 'outline'],
  ['fillalertbellon', 'bell-on', 'alert', 'fill'],
  ['fillcommunicationphone', 'phone', 'communication', 'fill'],
  ['fillalerterror', 'error', 'alert', 'fill'],
  ['outlinenavigationappgrid', 'app-grid', 'navigation', 'outline'],
  ['fillcontentviewtiles', 'view-tiles', 'content', 'fill'],
  ['fillcontentviewtable', 'view-table', 'content', 'fill'],
  ['outlinefilefilepdf', 'file-pdf', 'file', 'outline'],
  ['outlinenavigationmenu', 'menu', 'navigation', 'outline'],
  ['outlinefilefileppt', 'file-ppt', 'file', 'outline'],
  ['outlinefilefilexls', 'file-xls', 'file', 'outline'],
  ['outlinefilefiledoc', 'file-doc', 'file', 'outline'],
  ['outlinefilefileother', 'file-other', 'file', 'outline'],
  ['fillnavigationarrowdown', 'arrow-down', 'navigation', 'fill'],
  ['outlinecommunicationnoise', 'noise', 'communication', 'outline'],
  ['outlinecontentreply', 'reply', 'content', 'outline'],
  ['fillcommunicationrecording', 'recording', 'communication', 'fill'],
  ['fillcontentshare', 'share', 'content', 'fill'],
  ['outlinecontentshare', 'share', 'content', 'outline'],
  [
    'outlinecommunicationscreensharepresentation',
    'screenshare-presentation',
    'communication',
    'outline',
  ],
  [
    'fillcommunicationspeakerbluetooth',
    'speaker-bluetooth',
    'communication',
    'fill',
  ],
  ['outlinecontentundo', 'undo', 'content', 'outline'],
  ['outlinecontentredo', 'redo', 'content', 'outline'],
  ['outlinenavigationrefresh', 'refresh', 'navigation', 'outline'],
  ['outlinecontentincomplete', 'incomplete', 'content', 'outline'],
  ['outlinecommunicationphonemute', 'phone-mute', 'communication', 'outline'],
  ['outlinecontentgif', 'gif', 'content', 'outline'],
  ['outlinefileimage', 'image', 'file', 'outline'],
  [
    'outlinenavigationarrowlinedown',
    'arrow-line-down',
    'navigation',
    'outline',
  ],
  [
    'outlinenavigationellipsesvertical',
    'ellipses-vertical',
    'navigation',
    'outline',
  ],
  ['outlineactioncalendar', 'calendar', 'action', 'outline'],
  ['outlineactionsortdescending', 'sort-descending', 'action', 'outline'],
  ['outlineactionsortascending', 'sort-ascending', 'action', 'outline'],
  ['fillcontentclosecircle', 'close-circle', 'content', 'fill'],
  ['fillcontentinteractionlog', 'interaction-log', 'content', 'fill'],
  ['outlinecommunicationemail', 'email', 'communication', 'outline'],
  ['outlinecontentaddressbook', 'address-book', 'content', 'outline'],
  ['outlinecommunicationcobrowse', 'co-browse', 'communication', 'outline'],
  ['outlinecontentcustomerjourney', 'customer-journey', 'content', 'outline'],
  ['fillnavigationarrowleft', 'arrow-left', 'navigation', 'fill'],
  ['fillactionpause', 'pause', 'action', 'fill'],
  ['outlinecommunicationtransfer', 'transfer', 'communication', 'outline'],
  ['outlinecontentautoanswer', 'auto-answer', 'content', 'outline'],
  ['outlinecommunicationdialin', 'dial-in', 'communication', 'outline'],
  [
    'outlinecommunicationjoinspacesroom',
    'join-spaces-room',
    'communication',
    'outline',
  ],
  ['outlinealertnotification', 'notification', 'alert', 'outline'],
  ['outlinecommunicationdeferinbox', 'defer-inbox', 'communication', 'outline'],
  ['outlinecontentcreditcard', 'credit-card', 'content', 'outline'],
  ['fillcontentcharts', 'charts', 'content', 'fill'],
  ['outlinecontentinvoice', 'invoice', 'content', 'outline'],
  ['outlinecontentlink', 'link', 'content', 'outline'],
  ['outlinenavigationarrowdown', 'arrow-down', 'navigation', 'outline'],
  ['outlinecommunicationvoicemail', 'voicemail', 'communication', 'outline'],
  ['outlinecommunicationdialpad', 'dialpad', 'communication', 'outline'],
  ['outlinecommunicationraisehand', 'raise-hand', 'communication', 'outline'],
  ['outlinecontentfilter', 'filter', 'content', 'outline'],
  ['outlinecommunicationbroadcast', 'broadcast', 'communication', 'outline'],
  ['fillcontentfilter', 'filter', 'content', 'fill'],
  ['fillcommunicationspeakerlow', 'speaker-low', 'communication', 'fill'],
  ['fillcommunicationspeakermedium', 'speaker-medium', 'communication', 'fill'],
  [
    'outlinenavigationarrowlineright',
    'arrow-line-right',
    'navigation',
    'outline',
  ],
  [
    'outlinenavigationarrowlineleft',
    'arrow-line-left',
    'navigation',
    'outline',
  ],
  ['outlineactionsortdefault', 'sort-default', 'action', 'outline'],
  [
    'outlinenavigationellipseshorizontal',
    'ellipses-horizontal',
    'navigation',
    'outline',
  ],
  ['outlineactiondashboardportal', 'dashboard-portal', 'action', 'outline'],
  ['outlineactionmonitoringtools', 'monitoring-tools', 'action', 'outline'],
  ['outlinecommunicationnumber', 'number', 'communication', 'outline'],
  [
    'outlinecommunicationsocialintegrations',
    'social-integrations',
    'communication',
    'outline',
  ],
  ['outlineactiondrag', 'drag', 'action', 'outline'],
  ['outlinecommunicationsip', 'sip', 'communication', 'outline'],
  ['fillactionsupport', 'support', 'action', 'fill'],
  ['outlinenavigationlastpage', 'last-page', 'navigation', 'outline'],
  ['outlinenavigationfirstpage', 'first-page', 'navigation', 'outline'],
  ['outlinealertbelldefault', 'bell-default', 'alert', 'outline'],
  ['outlinecontentaddcircle', 'add-circle', 'content', 'outline'],
  ['outlinealertinfo', 'info', 'alert', 'outline'],
  ['outlinecontentcopy', 'copy', 'content', 'outline'],
  ['outlinecontentobservestop', 'observe-stop', 'content', 'outline'],
  ['outlinenavigationarrowright', 'arrow-right', 'navigation', 'outline'],
  ['outlinenavigationarrowleft', 'arrow-left', 'navigation', 'outline'],
  ['outlinenavigationarrowup', 'arrow-up', 'navigation', 'outline'],
  ['outlineotherapi', 'api', 'other', 'outline'],
  ['outlinecontenttrash', 'trash', 'content', 'outline'],
  ['outlinecontentcheck', 'check', 'content', 'outline'],
  ['outlineaccountbusiness', 'business', 'account', 'outline'],
  ['outlineaccountcontact', 'contact', 'account', 'outline'],
  ['outlineaccountcrown', 'crown', 'account', 'outline'],
  ['outlineaccountmeetings', 'meetings', 'account', 'outline'],
  ['outlineaccountmemberadd', 'member-add', 'account', 'outline'],
  ['outlineaccountsubaccounts', 'sub-accounts', 'account', 'outline'],
  ['fillcommunicationdirectmessage', 'direct-message', 'communication', 'fill'],
  ['fillaccountsupervisor', 'supervisor', 'account', 'fill'],
  ['fillaccountwaiting', 'waiting', 'account', 'fill'],
  ['outlineactionaudit', 'audit', 'action', 'outline'],
  ['outlineactionattach', 'attach', 'action', 'outline'],
  ['outlineactionextendtime', 'extend-time', 'action', 'outline'],
  ['outlineactionclonepreview', 'clone-preview', 'action', 'outline'],
  ['outlinefiledownload', 'download', 'file', 'outline'],
  ['fillactionplay', 'play', 'action', 'fill'],
  ['outlineactionhome', 'home', 'action', 'outline'],
  ['outlineactionswitchscreen', 'switch-screen', 'action', 'outline'],
  ['outlineactionviewminimize', 'view-minimize', 'action', 'outline'],
  ['fillactioncalculator', 'calculator', 'action', 'fill'],
  ['outlineactionshare', 'share', 'action', 'outline'],
  ['outlineactionhelpsupport', 'help-support', 'action', 'outline'],
  ['outlineactionzoomin', 'zoom-in', 'action', 'outline'],
  ['outlineactionviewfull', 'view-full', 'action', 'outline'],
  ['outlineactionworkflow', 'workflow', 'action', 'outline'],
  ['outlineactionsignin', 'sign-in', 'action', 'outline'],
  ['outlineactiondragarea', 'drag-area', 'action', 'outline'],
  ['outlineactionscreenpopclose', 'screen-pop-close', 'action', 'outline'],
  ['outlineactioncapture', 'capture', 'action', 'outline'],
  ['outlineactionsearch', 'search', 'action', 'outline'],
  ['outlinecontentsupportticket', 'support-ticket', 'content', 'outline'],
  ['outlineactionchangepassword', 'change-password', 'action', 'outline'],
  ['outlineactionsettings', 'settings', 'action', 'outline'],
  ['outlineactionhistory', 'history', 'action', 'outline'],
  ['outlineaccountmemberstandard', 'member-standard', 'account', 'outline'],
  ['outlineactionscreenpop', 'screen-pop', 'action', 'outline'],
  ['outlineactionhistorysearch', 'history-search', 'action', 'outline'],
  ['outlineactionglobal', 'global', 'action', 'outline'],
  ['outlineactionsignout', 'sign-out', 'action', 'outline'],
  ['outlineactionzoomout', 'zoom-out', 'action', 'outline'],
  ['fillactionconfigure', 'configure', 'action', 'fill'],
  ['outlinealertwarning', 'warning', 'alert', 'outline'],
  ['outlinealerterror', 'error', 'alert', 'outline'],
  ['outlineactionprint', 'print', 'action', 'outline'],
  ['outlinecommunicationdeferin', 'defer-in', 'communication', 'outline'],
  ['outlineactionpreferences', 'preferences', 'action', 'outline'],
  [
    'outlinecommunicationicconferencewifi',
    'ic-conference-wifi',
    'communication',
    'outline',
  ],
  ['outlineactiondetach', 'detach', 'action', 'outline'],
  ['outlinecommunicationskills', 'skills', 'communication', 'outline'],
  [
    'outlinecommunicationqueuerecall',
    'queue-recall',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationqueueinternalcall',
    'queue-internal-call',
    'communication',
    'outline',
  ],
  ['outlinecommunicationlisten', 'listen', 'communication', 'outline'],
  ['outlinecommunicationtvscreen', 'tv-screen', 'communication', 'outline'],
  ['outlinecommunicationbargein', 'barge-in', 'communication', 'outline'],
  [
    'outlinecommunicationmeetingcontrols',
    'meeting-controls',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationreleasecontrol',
    'release-control',
    'communication',
    'outline',
  ],
  ['outlinecommunicationsplitcall', 'split-call', 'communication', 'outline'],
  [
    'outlinecommunicationconferencecall',
    'conference-call',
    'communication',
    'outline',
  ],
  ['outlinecommunicationmerge', 'merge', 'communication', 'outline'],
  [
    'outlinecommunicationholdcallon',
    'hold-call-on',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationcenterfocus',
    'center-focus',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationholdcalloff',
    'hold-call-off',
    'communication',
    'outline',
  ],
  ['outlinecommunicationwhisper', 'whisper', 'communication', 'outline'],
  ['outlinecommunicationheadphones', 'headphones', 'communication', 'outline'],
  ['outlinecommunicationavsettings', 'av-settings', 'communication', 'outline'],
  ['outlinecommunicationunparkcall', 'unpark-call', 'communication', 'outline'],
  [
    'outlinecommunicationnetworkquality',
    'network-quality',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationvoicemaillock',
    'voicemail-lock',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationphonecalllogs',
    'phone-call-logs',
    'communication',
    'outline',
  ],
  ['outlinecommunicationspeakeroff', 'speaker-off', 'communication', 'outline'],
  ['outlinecommunicationmakecall', 'make-call', 'communication', 'outline'],
  [
    'outlinecommunicationwebchatmissed',
    'web-chat-missed',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationpresentationonly',
    'presentation-only',
    'communication',
    'outline',
  ],
  ['outlinecommunicationparkcall', 'park-call', 'communication', 'outline'],
  [
    'outlinecommunicationmessagesoutgoing',
    'messages-outgoing',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationheadphonesbluetooth',
    'headphones-bluetooth',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationsmsincoming',
    'sms-incoming',
    'communication',
    'outline',
  ],
  ['outlinecommunicationsmsmissed', 'sms-missed', 'communication', 'outline'],
  ['outlinecommunicationavblock', 'av-block', 'communication', 'outline'],
  ['outlinecommunicationaddcall', 'add-call', 'communication', 'outline'],
  [
    'outlinecommunicationsmsalerting',
    'sms-alerting',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationtesttospeech',
    'test-to-speech',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationcallforward',
    'call-forward',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationqueueexternalcall',
    'queue-external-call',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationphonedialin',
    'phone-dial-in',
    'communication',
    'outline',
  ],
  ['outlinecommunicationsmsactive', 'sms-active', 'communication', 'outline'],
  [
    'outlinecommunicationrecallmissed',
    'recall-missed',
    'communication',
    'outline',
  ],
  ['outlinecommunicationendcall', 'end-call', 'communication', 'outline'],
  [
    'outlinecommunicationvoicecalloutgoing',
    'voice-call-outgoing',
    'communication',
    'outline',
  ],
  ['outlinecommunicationmobile', 'mobile', 'communication', 'outline'],
  [
    'outlinecommunicationmessagesincoming',
    'messages-incoming',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationsupportlivechat',
    'support-live-chat',
    'communication',
    'outline',
  ],
  ['outlinecommunicationphonehard', 'phone-hard', 'communication', 'outline'],
  ['fillcommunicationcallobserver', 'call-observer', 'communication', 'fill'],
  [
    'outlinecommunicationcameracontrol',
    'camera-control',
    'communication',
    'outline',
  ],
  ['outlinecommunicationdeferout', 'defer-out', 'communication', 'outline'],
  [
    'outlinecommunicationsmsoutbound',
    'sms-outbound',
    'communication',
    'outline',
  ],
  [
    'outlinecommunicationsendtoqueue',
    'send-to-queue',
    'communication',
    'outline',
  ],
  ['outlinecommunicationspeakermax', 'speaker-max', 'communication', 'outline'],
  [
    'outlinecommunicationrequestcontrol',
    'request-control',
    'communication',
    'outline',
  ],
  ['outlinestatussocketconnected', 'socket-connected', 'status', 'outline'],
  ['fillstatusdisconnected', 'disconnected', 'status', 'fill'],
  ['fillstatusbusy', 'busy', 'status', 'fill'],
  ['fillstatusoffline', 'offline', 'status', 'fill'],
  ['fillstatusdonotdisturb', 'do-not-disturb', 'status', 'fill'],
  ['fillstatusavailable', 'available', 'status', 'fill'],
  ['outlinesocialfacebook', 'facebook', 'social', 'outline'],
  ['outlinenavigationarrowlineup', 'arrow-line-up', 'navigation', 'outline'],
  [
    'outlinestatussocketdisconnected',
    'socket-disconnected',
    'status',
    'outline',
  ],
  ['fillnavigationarrowup', 'arrow-up', 'navigation', 'fill'],
  ['outlineeditorparagraph', 'paragraph', 'editor', 'outline'],
  ['outlinelogoasana', 'asana', 'logo', 'outline'],
  ['outlineothershoppingcart', 'shopping-cart', 'other', 'outline'],
  ['fillnavigationarrowright', 'arrow-right', 'navigation', 'fill'],
  ['outlinefilegoogledrive', 'google-drive', 'file', 'outline'],
  ['outlinefilefolder', 'folder', 'file', 'outline'],
  ['outlinefileupload', 'upload', 'file', 'outline'],
  ['outlinecontentminus', 'minus', 'content', 'outline'],
  ['outlinesocialinstagram', 'instagram', 'social', 'outline'],
  ['outlinefilefilezip', 'file-zip', 'file', 'outline'],
  ['outlinecontentsignature', 'signature', 'content', 'outline'],
  ['outlinefilefiletext', 'file-text', 'file', 'outline'],
  ['outlinecontentpinon', 'pin-on', 'content', 'outline'],
  ['outlinesocialsocialactive', 'social-active', 'social', 'outline'],
  ['outlinefilefile', 'file', 'file', 'outline'],
  [
    'outlinecontenthistoricalreports',
    'historical-reports',
    'content',
    'outline',
  ],
  ['outlineeditorcapslock', 'caps-lock', 'editor', 'outline'],
  ['outlineeditoralignleft', 'align-left', 'editor', 'outline'],
  ['outlineeditorquote', 'quote', 'editor', 'outline'],
  [
    'outlinecontentsugggestedcontent',
    'sugggested-content',
    'content',
    'outline',
  ],
  ['outlineeditoraligncenter', 'align-center', 'editor', 'outline'],
  ['outlineeditorstrikethrough', 'strikethrough', 'editor', 'outline'],
  ['outlinecontentadd', 'add', 'content', 'outline'],
  ['outlinesocialfacebookmessenger', 'facebook-messenger', 'social', 'outline'],
  ['outlinesocialtwitter', 'twitter', 'social', 'outline'],
  ['outlineeditorlistordered', 'list-ordered', 'editor', 'outline'],
  ['outlineeditorbold', 'bold', 'editor', 'outline'],
  ['outlineeditorformatting', 'formatting', 'editor', 'outline'],
  ['outlineeditorunderline', 'underline', 'editor', 'outline'],
  ['outlineeditoritalic', 'italic', 'editor', 'outline'],
  ['outlineeditorwysiwyg', 'wysiwyg', 'editor', 'outline'],
  ['outlinefilefilejson', 'file-json', 'file', 'outline'],
  ['fillcontentaddress', 'address', 'content', 'fill'],
  ['outlineeditoralignright', 'align-right', 'editor', 'outline'],
  ['outlineeditorh2', 'h2', 'editor', 'outline'],
  ['outlinecontentminutes', 'minutes', 'content', 'outline'],
  ['outlinefileoffice365', 'office-365', 'file', 'outline'],
  ['outlinecontentdisposition', 'disposition', 'content', 'outline'],
  ['outlinecontentbackspace', 'backspace', 'content', 'outline'],
  ['outlinecontentpinoff', 'pin-off', 'content', 'outline'],
  ['fillothershield', 'shield', 'other', 'fill'],
  ['outlinefilefilehtml', 'file-html', 'file', 'outline'],
  ['fillcontentcomments', 'comments', 'content', 'fill'],
  ['outlineeditoratsymbol', 'at-symbol', 'editor', 'outline'],
  ['outlinecontentstarhalffilled', 'star-half-filled', 'content', 'outline'],
  ['outlineeditorh1', 'h1', 'editor', 'outline'],
  ['outlinecontentlayout', 'layout', 'content', 'outline'],
  ['outlineotherintegrations', 'integrations', 'other', 'outline'],
  ['outlinelogosalesforce', 'salesforce', 'logo', 'outline'],
  ['fillcontentcrm', 'crm', 'content', 'fill'],
  ['outlineeditorlistunordered', 'list-unordered', 'editor', 'outline'],
  ['outlineaccountaccounts', 'accounts', 'account', 'outline'],
  ['outlinesocialyoutube', 'youtube', 'social', 'outline'],
  ['outlinecommunicationqueue', 'queue', 'communication', 'outline'],
  ['fillcommunicationspeakermax', 'speaker-max', 'communication', 'fill'],
  ['outlineaccountaccountscircle', 'accounts-circle', 'account', 'outline'],
  ['fillactionhelpsupport', 'help-support', 'action', 'fill'],
  ['outlineactionnoresults', 'no-results', 'action', 'outline'],
  ['fillactionhome', 'home', 'action', 'fill'],
  ['outlineactionidea', 'idea', 'action', 'outline'],
  ['outlinecontentcontactflow', 'contact-flow', 'content', 'outline'],
  ['fillstatusaway', 'away', 'status', 'fill'],
  ['outlineeditorcode', 'code', 'editor', 'outline'],
  ['outlinecontentobserveon', 'observe-on', 'content', 'outline'],
  ['filleditorquote', 'quote', 'editor', 'fill'],
  ['fillcontentcomplete', 'complete', 'content', 'fill'],
  ['fillactionsend', 'send', 'action', 'fill'],
  ['outlinecontentemoji', 'emoji', 'content', 'outline'],
  ['fillcommunicationvideoon', 'video-on', 'communication', 'fill'],
  ['outlinecommunicationaudiooff', 'audio-off', 'communication', 'outline'],
  ['outlinecommunicationaudioon', 'audio-on', 'communication', 'outline'],
  ['outlinecommunicationvideooff', 'video-off', 'communication', 'outline'],
  ['outlinecommunicationvideoon', 'video-on', 'communication', 'outline'],
  [
    'outlinecommunicationscreenshareoff',
    'screenshare-off',
    'communication',
    'outline',
  ],
  ['fillcommunicationendcall', 'end-call', 'communication', 'fill'],
  [
    'outlinecommunicationscreenshareon',
    'screenshare-on',
    'communication',
    'outline',
  ],
  ['fillcontentstarfilled', 'star-filled', 'content', 'fill'],
  ['outlineactionlock', 'lock', 'action', 'outline'],
];
