// this file is auto-generated, DO NOT modify it
 export const icons = [
  {
    name: "chevron-right",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "forward-skip",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "user-add",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "missed-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "ic-conference-wifi",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "conference-call",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "agents",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  { name: "error", bidirectional: false, category: "alert", animated: false },
  { name: "info", bidirectional: false, category: "alert", animated: false },
  {
    name: "contact",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  { name: "add", bidirectional: false, category: "content", animated: false },
  {
    name: "layout-immersive",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "raise-hand",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "posts", bidirectional: false, category: "content", animated: false },
  {
    name: "audio-filled",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "audio-on",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "recording-off",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "error-filled",
    bidirectional: false,
    category: "alert",
    animated: false,
  },
  {
    name: "audio-off",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "transfer-forward",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "warning-filled",
    bidirectional: false,
    category: "alert",
    animated: false,
  },
  {
    name: "menu",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "chevron-down",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  {
    name: "exit-left",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "arrow-left",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "video-on",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "fullscreen-off",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  { name: "warning", bidirectional: false, category: "alert", animated: false },
  { name: "check", bidirectional: false, category: "content", animated: false },
  {
    name: "layout-grid",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "emergency",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "strikethrough",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "app-grid",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  {
    name: "shape-circle",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "bar-chart",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  {
    name: "chart-lines",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "digital",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chart-gauge",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "preferences",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "comments",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "call-logs-rtl",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "home", bidirectional: false, category: "action", animated: false },
  { name: "key", bidirectional: false, category: "action", animated: false },
  {
    name: "noise",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "speaker-high",
    bidirectional: true,
    category: "communication",
    animated: true,
  },
  { name: "file", bidirectional: false, category: "file", animated: false },
  { name: "edit", bidirectional: false, category: "content", animated: false },
  { name: "reply", bidirectional: true, category: "content", animated: false },
  {
    name: "reply-all",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  { name: "awfos", bidirectional: false, category: "content", animated: false },
  { name: "skills", bidirectional: false, category: "action", animated: false },
  {
    name: "list-number",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "business",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  { name: "music", bidirectional: false, category: "content", animated: false },
  {
    name: "workflow",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "integrations",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "bot",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "bot-agent",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "filter",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "layout-active-speaker",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "layout-concert",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "layout-thumbnail-horizontal",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "analytics",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "layout-automatic",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chevron-up",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  {
    name: "headphones",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "defer-in",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "trash", bidirectional: false, category: "content", animated: false },
  {
    name: "ellipses-horizontal",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  { name: "spinner", bidirectional: false, category: "other", animated: false },
  { name: "close", bidirectional: false, category: "content", animated: false },
  {
    name: "email",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-make",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "available-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "star-filled",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "available",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  { name: "star", bidirectional: false, category: "content", animated: false },
  {
    name: "call-outbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "hold-off",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "dtmf",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sub-accounts",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "hospitality",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "incognito",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "incognito-off",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "chat",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "attach", bidirectional: false, category: "file", animated: false },
  {
    name: "task-incomplete",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  { name: "image", bidirectional: false, category: "file", animated: false },
  {
    name: "view-on",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "play-filled",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  { name: "file-doc", bidirectional: false, category: "file", animated: false },
  {
    name: "address",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  { name: "global", bidirectional: false, category: "action", animated: false },
  {
    name: "view-off",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "code-cloud",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "conference-screen",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "refresh",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  {
    name: "arrow-right",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "center-focus",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chevron-left",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "calendar",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "view-tiles",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "address-book",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  {
    name: "control-release",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "sip",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "fullscreen-on",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "voicemail",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "search", bidirectional: false, category: "action", animated: false },
  {
    name: "dialpad",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "help", bidirectional: true, category: "action", animated: false },
  {
    name: "filter-filled",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "billboard-chart",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  { name: "undo", bidirectional: true, category: "content", animated: false },
  { name: "unlock", bidirectional: false, category: "action", animated: false },
  {
    name: "export-logs",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  { name: "minus", bidirectional: false, category: "content", animated: false },
  { name: "coach", bidirectional: false, category: "content", animated: false },
  {
    name: "settings",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "user-group",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "message-read",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "defer-out",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "file-pdf", bidirectional: false, category: "file", animated: false },
  {
    name: "busy-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "ellipses-vertical",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  { name: "download", bidirectional: false, category: "file", animated: false },
  {
    name: "callback",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "file-txt", bidirectional: false, category: "file", animated: false },
  {
    name: "closed-caption",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "send", bidirectional: true, category: "action", animated: false },
  { name: "lock", bidirectional: false, category: "action", animated: false },
  {
    name: "broadcast",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "spaces",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "upload", bidirectional: false, category: "file", animated: false },
  { name: "link", bidirectional: false, category: "content", animated: false },
  { name: "sort", bidirectional: false, category: "action", animated: false },
  { name: "copy", bidirectional: false, category: "content", animated: false },
  {
    name: "stop-filled",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "configure",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  { name: "drag", bidirectional: false, category: "action", animated: false },
  {
    name: "hold-on",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-outbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "away", bidirectional: false, category: "status", animated: false },
  { name: "play", bidirectional: false, category: "action", animated: false },
  {
    name: "recall-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "camera", bidirectional: false, category: "action", animated: false },
  {
    name: "window-detach",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "recording-on",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "window-attach",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "sentiment-happy",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "listen",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "history-reports",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "clear-day",
    bidirectional: false,
    category: "weather",
    animated: false,
  },
  {
    name: "call-logs",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "camera-ext-on",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "custom",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "billboard",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "supervisor",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  { name: "redo", bidirectional: true, category: "content", animated: false },
  {
    name: "screenpop-on",
    bidirectional: true,
    category: "action",
    animated: false,
  },
  {
    name: "call-end",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-transfer",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-add",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "user-conference",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "customer-journey",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "away-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "social-media",
    bidirectional: false,
    category: "social",
    animated: false,
  },
  { name: "bold", bidirectional: false, category: "editor", animated: false },
  {
    name: "noise-off",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "history",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "dashboard",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "screen-min",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  { name: "support", bidirectional: true, category: "action", animated: false },
  {
    name: "chart-area",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  { name: "folder", bidirectional: false, category: "file", animated: false },
  {
    name: "notifications-off",
    bidirectional: false,
    category: "alert",
    animated: false,
  },
  {
    name: "arrow-down",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  {
    name: "special-character",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "notifications-on",
    bidirectional: false,
    category: "alert",
    animated: false,
  },
  { name: "archive", bidirectional: false, category: "file", animated: false },
  {
    name: "contact-filled",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "timeline",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "messaging",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-dial-in",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "redial",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "noise-1",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "clipboard",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  {
    name: "coach-off",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "chat-filled",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "typing",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "chat-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "text", bidirectional: false, category: "editor", animated: false },
  {
    name: "call-inbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "video-off",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "arrow-up",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  {
    name: "collapse-all",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "offline-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "work-start",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "speaker-medium",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "video-not-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "align-left",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "align-bottom",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  { name: "shield", bidirectional: false, category: "other", animated: false },
  {
    name: "page-first",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "align-distribute-horizontal",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "camera-flip",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "social",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-not-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-inbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-outbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-alerting",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-connected",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-pending",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "forward-fast",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "backward-fast",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "backward-skip",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "speaker-low",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "thumbs-down",
    bidirectional: false,
    category: "social",
    animated: false,
  },
  {
    name: "align-top",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "align-right",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "awfos-rtl",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "audit-rtl",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "layout-thumbnail-vertical",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "reason-codes",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  { name: "file-rtl", bidirectional: false, category: "file", animated: false },
  {
    name: "user-details-rtl",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "audio-lock",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "audio-warning",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "video-warning",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-forwarded-rtl",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "cloudy-few",
    bidirectional: false,
    category: "weather",
    animated: false,
  },
  {
    name: "clear-night",
    bidirectional: false,
    category: "weather",
    animated: false,
  },
  {
    name: "cloudy-scattered",
    bidirectional: false,
    category: "weather",
    animated: false,
  },
  {
    name: "thunderstorm",
    bidirectional: false,
    category: "weather",
    animated: false,
  },
  { name: "snow", bidirectional: false, category: "weather", animated: false },
  { name: "mist", bidirectional: false, category: "weather", animated: false },
  {
    name: "showers",
    bidirectional: false,
    category: "weather",
    animated: false,
  },
  {
    name: "email-forwarded",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "thresholds",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "custom-not-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "work-code",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "work-end",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "custom-inbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "custom-outbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "custom-alerting",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "interaction-details",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "computer",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-inbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "pom",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "not-available",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "image-broken",
    bidirectional: false,
    category: "file",
    animated: false,
  },
  {
    name: "picture-in-picture",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "custom-pending",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "custom-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "playback",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "chart-bubbles",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "user-waiting",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "layout-custom",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "widget-layout",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "redirect",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "widget-overview",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "sign-in",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "whisper",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "file-json",
    bidirectional: false,
    category: "file",
    animated: false,
  },
  {
    name: "history-search",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "queue-internal-call",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "crown", bidirectional: false, category: "account", animated: false },
  {
    name: "support-ticket",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  { name: "share", bidirectional: false, category: "action", animated: false },
  {
    name: "queue-send-to",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "offline",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "disconnected",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "socket-connected",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "phone-hard",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "socket-disconnected",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "camera-control",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "av-block",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "av-settings",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-split",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "speaker-off",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "merge",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "presentation-only",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "tv-screen",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "mobile",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "queue-recall",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "queue-external-call",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "signature",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "pin-on",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "layout",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "pin-off",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "paragraph",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "backspace",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  { name: "file-zip", bidirectional: false, category: "file", animated: false },
  {
    name: "caps-lock",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "dashboard-filled",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "defer-inbox",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "page-last",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "pie-chart",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "invoice",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  { name: "gif", bidirectional: false, category: "content", animated: false },
  {
    name: "sms-not-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-not-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "format-collapse",
    bidirectional: true,
    category: "editor",
    animated: false,
  },
  { name: "code", bidirectional: false, category: "editor", animated: false },
  { name: "quote", bidirectional: false, category: "editor", animated: false },
  {
    name: "underline",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "list-bullet",
    bidirectional: true,
    category: "editor",
    animated: false,
  },
  {
    name: "clone-preview",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "italics",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  { name: "file-png", bidirectional: false, category: "file", animated: false },
  { name: "select", bidirectional: false, category: "action", animated: false },
  { name: "save", bidirectional: false, category: "action", animated: false },
  {
    name: "add-circle",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "sentiment-sad",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "call-mute",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "time-extend",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "screen-swap",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "do-not-disturb",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "do-not-disturb-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  { name: "file-ppt", bidirectional: false, category: "file", animated: false },
  {
    name: "calendar-filled",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "user-details",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "star-half-filled",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  {
    name: "meeting-controls",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-pending",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "thumbs-up",
    bidirectional: false,
    category: "social",
    animated: false,
  },
  {
    name: "font-highlight",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "zoom-in",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "zoom-out",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  { name: "graph", bidirectional: true, category: "content", animated: false },
  {
    name: "cloudy",
    bidirectional: false,
    category: "weather",
    animated: false,
  },
  { name: "usb", bidirectional: false, category: "other", animated: false },
  {
    name: "expand-all",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "video-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "align-center-vertical",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "align-center-horizontal",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "align-distribute-vertical",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  { name: "file-xls", bidirectional: false, category: "file", animated: false },
  {
    name: "arrow-fill-down",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  { name: "idea", bidirectional: false, category: "action", animated: false },
  {
    name: "chat-inbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "barge-in",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "audio-on-2",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "font-size-he",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "audio-on-3",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "font-size-zh",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "audio-on-1",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "font-size-ko",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-predefined-ko",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-size-ar",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-size-ja",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-expand-ar",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-expand-ja",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-expand-zh",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-expand-he",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-expand-ko",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-color-ko",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-color-ar",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-color-he",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-color-ja",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-color-zh",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-family-ar",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-family-ko",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-family-he",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-predefined-zh",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-remove-zh",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-remove-ko",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-highlight-zh",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-family-zh",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-family-ja",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-highlight-he",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-collapse-ko",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-collapse-ar",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-predefined-ar",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-predefined-ja",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-predefined-he",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-remove-he",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-remove-ja",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-highlight-ko",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-collapse-he",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-highlight-ja",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-remove-ar",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-collapse-zh",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-highlight-ar",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-collapse-ja",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "mobile-not-paired",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "mobile-wireless",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "label", bidirectional: false, category: "content", animated: false },
  {
    name: "mobile-paired",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "camera-ext-off",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "link-remove",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "font-family",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-remove",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "font-color",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "format-predefined",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "indent-increase",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "indent-decrease",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "line-break",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "speaker-wireless",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "headphones-wireless",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "superscript",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "lock-filled",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "inbound-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "outbound-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "connected-filled",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "notifications-alerting",
    bidirectional: false,
    category: "alert",
    animated: false,
  },
  {
    name: "notifications-on-filled",
    bidirectional: false,
    category: "alert",
    animated: false,
  },
  {
    name: "messaging-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-alerting",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-inbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "custom-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "custom-connected",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-not-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-connected",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-outbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "network-quality-0",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-pending",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "legal", bidirectional: false, category: "content", animated: false },
  {
    name: "email-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "video-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-connected",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chat-connected",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-connected",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-connected",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "video-connected",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "typing-2",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "typing-3",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "typing-1",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "speaker-none",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "network-quality-3",
    bidirectional: true,
    category: "communication",
    animated: true,
  },
  {
    name: "network-quality-2",
    bidirectional: true,
    category: "communication",
    animated: true,
  },
  {
    name: "spaces-filled",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "noise-2",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "noise-3",
    bidirectional: false,
    category: "communication",
    animated: true,
  },
  {
    name: "network-quality-1",
    bidirectional: true,
    category: "communication",
    animated: true,
  },
  {
    name: "screen-max",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "email-alerting",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-inbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-open",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-not-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-pending",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-pending",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-outbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chart-donut",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "font-size",
    bidirectional: true,
    category: "editor",
    animated: false,
  },
  {
    name: "shape-circle-filled",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "line-straight",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "shape-square-filled",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  { name: "erase", bidirectional: false, category: "action", animated: false },
  {
    name: "shape-square",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  { name: "clean", bidirectional: false, category: "action", animated: false },
  {
    name: "format-expand",
    bidirectional: true,
    category: "editor",
    animated: false,
  },
  {
    name: "sentiment-very-happy",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "at-symbol",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  { name: "print", bidirectional: false, category: "action", animated: false },
  { name: "audit", bidirectional: false, category: "action", animated: false },
  {
    name: "chat-missed",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "change-password",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "suggested",
    bidirectional: true,
    category: "content",
    animated: false,
  },
  {
    name: "chat-not-ready",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chat-outbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chat-alerting",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chat-pending",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "heading-2",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "list-number-rtl",
    bidirectional: true,
    category: "editor",
    animated: false,
  },
  {
    name: "video-inbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "wifi",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "video-alerting",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-alerting",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "voicemail-private",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "arrow-fill-left",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "arrow-fill-up",
    bidirectional: false,
    category: "navigation",
    animated: false,
  },
  {
    name: "arrow-fill-right",
    bidirectional: true,
    category: "navigation",
    animated: false,
  },
  {
    name: "control-request",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "auto-answer",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "qr-code",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  {
    name: "network-quality",
    bidirectional: true,
    category: "communication",
    animated: true,
  },
  {
    name: "alignment-center",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "video-pending",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "crm", bidirectional: false, category: "content", animated: false },
  {
    name: "disposition-code",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  { name: "file-jpg", bidirectional: false, category: "file", animated: false },
  {
    name: "video-outbound",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "file-avi", bidirectional: false, category: "file", animated: false },
  {
    name: "file-html",
    bidirectional: false,
    category: "file",
    animated: false,
  },
  {
    name: "alignment-right",
    bidirectional: true,
    category: "editor",
    animated: false,
  },
  {
    name: "credit-card",
    bidirectional: false,
    category: "content",
    animated: false,
  },
  { name: "file-mp4", bidirectional: false, category: "file", animated: false },
  {
    name: "sentiment-neutral",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "heading-1",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  { name: "busy", bidirectional: false, category: "status", animated: false },
  {
    name: "sentiment-very-sad",
    bidirectional: false,
    category: "other",
    animated: false,
  },
  {
    name: "screenshare-off",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "cart", bidirectional: false, category: "other", animated: false },
  {
    name: "queue",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "screenshare-on",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "forward",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  {
    name: "bridged-line-appearance",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "bounce", bidirectional: false, category: "status", animated: false },
  {
    name: "screenpop-off",
    bidirectional: true,
    category: "action",
    animated: false,
  },
  {
    name: "co-browse",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "alignment-left",
    bidirectional: true,
    category: "editor",
    animated: false,
  },
  {
    name: "call-alerting",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "calculator",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "audio-jack",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "audio-incoming",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "audio-outgoing",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-incoming",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "call-outgoing",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chat-incoming",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "chat-outgoing",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-incoming",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "email-outgoing",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-incoming",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "messaging-outgoing",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-incoming",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "sms-outgoing",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-incoming",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "social-outgoing",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "video-incoming",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  {
    name: "video-outgoing",
    bidirectional: false,
    category: "communication",
    animated: false,
  },
  { name: "user", bidirectional: false, category: "account", animated: false },
  {
    name: "analytics-filled",
    bidirectional: false,
    category: "action",
    animated: false,
  },
  {
    name: "after-call-work",
    bidirectional: false,
    category: "status",
    animated: false,
  },
  { name: "cell", bidirectional: true, category: "content", animated: false },
  { name: "row", bidirectional: true, category: "content", animated: false },
  { name: "column", bidirectional: true, category: "content", animated: false },
  { name: "table", bidirectional: true, category: "content", animated: false },
  { name: "cut", bidirectional: false, category: "content", animated: false },
  {
    name: "mic-extended-off",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "mic-extended-on",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "vdn-incoming-call",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "user-return",
    bidirectional: false,
    category: "account",
    animated: false,
  },
  {
    name: "list-number-complete",
    bidirectional: false,
    category: "editor",
    animated: false,
  },
  {
    name: "zoom-default",
    bidirectional: true,
    category: "action",
    animated: false,
  },
  {
    name: "call-sms",
    bidirectional: true,
    category: "communication",
    animated: false,
  },
  {
    name: "table-insert",
    bidirectional: true,
    category: "action",
    animated: false,
  },
  {
    name: "table-delete",
    bidirectional: true,
    category: "action",
    animated: false,
  },
];
