name: Changelog check
on: [pull_request]
jobs:
  build:
    name: Changelog check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes to SCSS files
        id: verify-changed-files
        uses: tj-actions/changed-files@v26.1
        with:
          files: |
            css-library/neo/neo-scss/**/*.scss
            css-library/neo/neo-scss/*.scss
            css-library/neo/changelog.md
      - name: exit with error if SCSS files changed without changelog update
        if: steps.verify-changed-files.outputs.any_changed == 'true' && !contains(steps.verify-changed-files.outputs.modified_files, 'changelog.md') && !contains(toJson(github.event.pull_request.labels.*.name), 'ignore-for-release')
        run: |
          echo "Please make sure you have updated `css-library/neo/changelog.md` if you have made changes to the Neo SCSS files"
          exit 1
      - name: request changes if SCSS files changed without using valid label on PR
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        if: steps.verify-changed-files.outputs.any_changed == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          valid-labels: "breaking-changes, additional-changes, bugs-report, new-features, ignore-for-release"
