name: Visual Integration Test
on: [pull_request]
jobs:
  playwright:
    name: 'Visual Tests using Playwright Docker Image'
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'
      - name: build
        run: yarn github
      - name: start server
        run: |
          yarn preview &
          sleep 5
          curl -I http://localhost:4321
      - name: run playwright test using docker image
        uses: kohlerdominik/docker-run-action@v1.1.0
        with:
          image: mcr.microsoft.com/playwright:v1.38.1-focal
          shell: /bin/bash
          workdir: /work/
          environment: |
            BASEURL=http://host.docker.internal:4321
          volumes: |
            ${{ github.workspace }}/playwright:/work
          options: |
            --add-host host.docker.internal:host-gateway
          run: |
            curl -I http://host.docker.internal:4321
            yarn
            yarn playwright test
      - name: upload artifacts on test failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: |
            playwright/playwright-report/
            playwright/test-results/
          retention-days: 7

